version: "3.9"

services:
  api:
    build: ./video-streaming-api-service
    env_file: ./video-streaming-api-service/.env
    ports: ["4000:4000"]
    depends_on: [redis, minio, mc]
    volumes:
      - ./video-streaming-api-service:/app
    command: sh -c "npm install && npm run dev"

  worker:
    build: ./video-processing-service
    env_file: ./video-processing-service/.env
    depends_on: [redis, minio]
    volumes:
      - ./video-processing-service:/app
    command: sh -c "npm install && npm run dev"

  web:
    build: ./video-streaming-web-client
    env_file: ./video-streaming-web-client/.env.local
    ports: ["3000:3000"]
    depends_on: [api]
    volumes:
      - ./video-streaming-web-client:/app
    command: sh -c "npm install && npm run dev"

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  # Local S3-compatible storage (MinIO)
  minio:
    image: minio/minio:RELEASE.2025-01-11T01-00-00Z # any recent is fine
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"  # S3 API
      - "9090:9090"  # Console
    volumes:
      - minio_data:/data

  # One-shot client to create the bucket on startup
  mc:
    image: minio/mc
    depends_on: [minio]
    entrypoint: >
      sh -c "
        /usr/bin/mc alias set local http://minio:9000 minio minio12345 &&
        /usr/bin/mc mb -p local/video &&
        /usr/bin/mc anonymous set download local/video || true
      "
    restart: "no"

volumes:
  minio_data: